apiVersion: v1
kind: ReplicaSet
metadata:
  name: ReplicaSet Template
  namespace: default
  labels:
        environment: production
spec:
  template:
    spec:
        automountServiceAccountToken: true
