apiVersion: v1
kind: StatefulSet
metadata:
  name: StatefulSet Template
  namespace: default
  labels:
        environment: production
spec:
  template:
    spec:
        automountServiceAccountToken: true

